FROM python:3.11-slim

WORKDIR /app

# HF Spaces runs containers as a non-root user with a writable /app only,
# and expects the app to listen on port 7860.
ENV PORT=7860
EXPOSE 7860

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

COPY api/ ./api/
COPY dashboard/static/ ./dashboard/static/
COPY agent/results/phase6_results.json ./agent/results/phase6_results.json

# dashboard/static/graphs/*.html (pre-rendered Pyvis subgraphs) must already
# exist before `docker build` -- generated by
# `python -m dashboard.precompute_case_graphs` (needs the full dev
# environment: torch/PyG/pyvis), NOT rebuilt inside this lightweight image.

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "7860"]
